// Generated by CoffeeScript 1.6.3
var syncFetch;

syncFetch = function(file, fn) {
  /* 获取资源文件*/

  var xhr;
  xhr = new XMLHttpRequest();
  xhr.open("GET", chrome.extension.getURL(file), false);
  xhr.onreadystatechange = function() {
    if (this.readyState === 4 && this.responseText !== "") {
      return fn(this.responseText);
    }
  };
  try {
    return xhr.send();
  } catch (_error) {}
};
