// Generated by CoffeeScript 1.6.3
var I18n, syncFetch;

syncFetch = function(file, fn) {
  /* 获取资源文件*/

  var xhr;
  xhr = new XMLHttpRequest();
  xhr.open("GET", chrome.extension.getURL(file), false);
  xhr.onreadystatechange = function() {
    if (this.readyState === 4 && this.responseText !== "") {
      return fn(this.responseText);
    }
  };
  try {
    return xhr.send();
  } catch (_error) {}
};

I18n = (function() {
  /* I18N*/

  var parseString;

  function I18n(locale) {
    var file,
      _this = this;
    this.locale = locale;
    file = "/_locales/" + this.locale + "/messages.json";
    syncFetch(file, function(text) {
      return _this.l10nData = JSON.parse(text);
    });
  }

  parseString = function(msgData, args) {
    if (msgData.message) {
      return msgData.message.replace(/\$\$/g, '$');
    }
    return args;
  };

  I18n.prototype.getMessage = function(id, args) {
    if (args == null) {
      args = '';
    }
    if (this.l10nData && id in this.l10nData) {
      return parseString(this.l10nData[id], args);
    }
    return '';
  };

  return I18n;

})();
