// Generated by CoffeeScript 1.6.3
var localStorageGet, localStorageSet;

localStorageGet = function(key, defaultValue) {
  var value;
  if (defaultValue == null) {
    defaultValue = false;
  }
  /* 读取本地数据*/

  value = localStorage.getItem(key);
  if (value) {
    return JSON.parse(value);
  }
  return defaultValue;
};

localStorageSet = function(key, value) {
  /* 设置本地数据*/

  return localStorage.setItem(key, JSON.stringify(value));
};
