// Generated by CoffeeScript 1.6.3
var isProtocol, isUrl, re;

re = null;

isUrl = function(str) {
  /* 判断字符串是否是URL*/

  var strRegex;
  strRegex = '^((https|http|ftp|rtsp|mms)?://)' + '?(([0-9a-z_!~*\'().&=+$%-]+: )?[0-9a-z_!~*\'().&=+$%-]+@)?' + '(([0-9]{1,3}.){3}[0-9]{1,3}' + '|' + '([0-9a-z_!~*\'()-]+.)*' + '([0-9a-z][0-9a-z-]{0,61})?[0-9a-z].' + '[a-z]{2,6})' + '(:[0-9]{1,4})?' + '((/?)|' + '(/[0-9a-z_!~*\'().;?:@&=+$,%#-]+)+/?)$';
  re = new RegExp(strRegex);
  return re.test(str);
};

isProtocol = function(str) {
  /* 判断是否包含协议*/

  var strRegex;
  strRegex = '^((https|http|ftp|rtsp|mms)?://)';
  re = new RegExp(strRegex);
  return re.test(str);
};
