// Generated by CoffeeScript 1.6.3
var isProtocol, isUrl, re;

re = null;

isUrl = function(str) {
  /* 判断字符串是否是URL*/

  re = /^((ht|f)tps?\:\/\/)?([a-z0-9]+\.)?[a-z0-9][a-z0-9-]*\.[a-z]{2,6}$/i;
  return re.test(str);
};

isProtocol = function(str) {
  /* 判断是否包含协议*/

  var strRegex;
  strRegex = '^((https|http|ftp|rtsp|mms)?://)';
  re = new RegExp(strRegex);
  return re.test(str);
};
