// Generated by CoffeeScript 1.6.3
/*
# RE utls
*/

if (!this.JU) {
  this.JU = {};
}

JU.isUrl = function(str) {
  /* 判断字符串是否是URL*/

  var re;
  re = /^((ht|f)tps?\:\/\/)?([a-z0-9]+\.)?[a-z0-9][a-z0-9-]*\.[a-z]{2,6}$/i;
  return re.test(str);
};

JU.isProtocol = function(str) {
  /* 判断是否包含协议*/

  var re, strRegex;
  strRegex = '^((https|http|ftp|rtsp|mms)?://)';
  re = new RegExp(strRegex);
  return re.test(str);
};
