// Generated by CoffeeScript 1.6.3
describe('localStorageGet', function() {
  return it('取值', function() {
    localStorage['a'] = '2';
    expect(JU.localStorageGet('a')).toEqual(2);
    return expect(JU.localStorageGet('b', '3')).toEqual('3');
  });
});

describe('localStorageSet', function() {
  return it('设值', function() {
    JU.localStorageSet('c', '5');
    return expect(localStorage['c']).toEqual('"5"');
  });
});

describe('boolen', function() {
  return it('设值', function() {
    JU.localStorageSet('c', true);
    expect(JU.localStorageGet('c')).toEqual(true);
    JU.localStorageSet('c', false);
    return expect(JU.localStorageGet('c')).toEqual(false);
  });
});
