// Generated by CoffeeScript 1.6.3
describe('re', function() {
  it('isUrl', function() {
    expect(isUrl('baidu')).toEqual(false);
    expect(isUrl('http://baidu')).toEqual(false);
    expect(isUrl('http://baidu.cn')).toEqual(true);
    expect(isUrl('www.baidu.com')).toEqual(true);
    expect(isUrl('baidu.com')).toEqual(true);
    expect(isUrl('baidu.cn')).toEqual(true);
    expect(isUrl('baidu.c')).toEqual(false);
    expect(isUrl('你好')).toEqual(false);
    return expect(isUrl('booking')).toEqual(false);
  });
  return it('isProtocol', function() {
    expect(isProtocol('www.baidu.com')).toEqual(false);
    return expect(isProtocol('http://www.baidu.com')).toEqual(true);
  });
});
