// Generated by CoffeeScript 1.6.3
describe('re', function() {
  return it('isUrl', function() {
    expect(isUrl('www.baidu.com')).toEqual(true);
    expect(isUrl('baidu.com')).toEqual(true);
    expect(isUrl('baidu.cn')).toEqual(true);
    expect(isUrl('baidu.c')).toEqual(false);
    return expect(isUrl('你好')).toEqual(false);
  });
});
