// Generated by CoffeeScript 1.6.2
'use strict';describe('utils', function() {
  describe('getId', function() {
    return it('getId', function() {
      expect(getId()).toEqual(1);
      expect(getId()).toEqual(2);
      return expect(getId()).toEqual(3);
    });
  });
  describe('findArray', function() {
    return it('对象查找', function() {
      var c;

      c = [
        {
          a: 1,
          b: 10
        }, {
          a: 2,
          b: 20
        }, {
          a: 3,
          b: 30
        }
      ];
      expect(findArray(c, 'a', 2).b).toEqual(20);
      return expect(findArray(c, 'a', [2, 3]).length).toEqual(2);
    });
  });
  describe('updateArray', function() {
    return it('数组替换', function() {
      var a;

      a = [1, 2, 3];
      expect(updateArray(a, 2, 9)).toEqual([1, 9, 3]);
      a = [1, 2, 2];
      expect(updateArray(a, 2, 9)).toEqual([1, 9, 9]);
      return expect(updateArray(a, 2, 9)).toEqual(a);
    });
  });
  describe('arrayRemove', function() {
    return it('数组对象删除', function() {
      var a;

      a = ['a', 'b', 'c'];
      arrayRemove(a, 'b');
      return expect(a).toEqual(['a', 'c']);
    });
  });
  describe('sortOn', function() {
    var c;

    c = [
      {
        a: 1,
        b: 4
      }, {
        a: 2,
        b: 3
      }, {
        a: 3,
        b: 2
      }, {
        a: 4,
        b: 1
      }
    ];
    it('a顺序', function() {
      sortOn(c, 'a');
      expect(c[0].a).toEqual(1);
      return expect(c[1].a).toEqual(2);
    });
    it('b顺序', function() {
      sortOn(c, 'b');
      expect(c[0].a).toEqual(4);
      return expect(c[1].a).toEqual(3);
    });
    it('a倒序', function() {
      sortOn(c, '-a');
      expect(c[0].a).toEqual(4);
      return expect(c[1].a).toEqual(3);
    });
    return it('b倒序', function() {
      sortOn(c, '-b');
      expect(c[0].a).toEqual(1);
      return expect(c[1].a).toEqual(2);
    });
  });
  describe('groupBy', function() {
    var c;

    c = [
      {
        a: 1,
        t: 1,
        g: 3
      }, {
        a: 2,
        t: 1,
        g: 4
      }, {
        a: 3,
        t: 2,
        g: 3
      }, {
        a: 4,
        t: 2,
        g: 4
      }
    ];
    it('t分组', function() {
      var g;

      g = groupBy(c, 't');
      expect(g[0].label).toEqual(1);
      expect(g[1].label).toEqual(2);
      expect(g[0].items[0].a).toEqual(1);
      expect(g[0].items[1].a).toEqual(2);
      expect(g[1].items[0].a).toEqual(3);
      return expect(g[1].items[1].a).toEqual(4);
    });
    return it('g分组', function() {
      var g;

      g = groupBy(c, 'g');
      expect(g[0].label).toEqual(3);
      expect(g[1].label).toEqual(4);
      expect(g[0].items[0].a).toEqual(1);
      expect(g[0].items[1].a).toEqual(3);
      expect(g[1].items[0].a).toEqual(2);
      return expect(g[1].items[1].a).toEqual(4);
    });
  });
  describe('localStorageGet', function() {
    return it('取值', function() {
      localStorage['a'] = '2';
      expect(localStorageGet('a')).toEqual(2);
      return expect(localStorageGet('b', '3')).toEqual('3');
    });
  });
  describe('localStorageSet', function() {
    return it('设值', function() {
      localStorageSet('c', '5');
      return expect(localStorage['c']).toEqual('"5"');
    });
  });
  return describe('boolen', function() {
    return it('设值', function() {
      localStorageSet('c', true);
      expect(localStorageGet('c')).toEqual(true);
      localStorageSet('c', false);
      return expect(localStorageGet('c')).toEqual(false);
    });
  });
});
